# Interpolacion 

In [69]:
from numpy import array
import numpy as np

# El polinomio de Lagrange 

In [66]:
def p(x,xi,yk,n): 
    result = [0,0,0]
    for k in range(0,n):        
        for i in range(0,n): 
            if(i!=k):
                result[k] = float(((x-xi[i])/(xi[k]-xi[i]))*yk[k])                
    suma = result[0]+result[1]
    print ('---->',suma )             

In [68]:
x=85
xi=array([80,90])
yk=array([0.9848,1])
n=2

p(x,xi,yk,n)


----> 0.9924


# El polinomio de Newton

# Mínimos cuadrados

In [70]:
F=np.array([
   [1.000, 3.871  ,4.000], 
   [1.000, 4.564  ,16.00], 
   [1.000, 5.123  ,49.00], 
   [1.000, 5.480  ,100.0]]) 

y=[7,12,20,40]

FT = F.transpose()
print(FT)
S=np.dot(FT, F)
print()
print(S)
print()

b=np.dot(FT, y)
print(b)
print()
x = np.linalg.inv(S)
print(x)
print()
c= np.dot(x, b)

print(c)

[[  1.      1.      1.      1.   ]
 [  3.871   4.564   5.123   5.48 ]
 [  4.     16.     49.    100.   ]]

[[4.0000000e+00 1.9038000e+01 1.6900000e+02]
 [1.9038000e+01 9.2090266e+01 8.8753500e+02]
 [1.6900000e+02 8.8753500e+02 1.2673000e+04]]

[  79.     403.525 5200.   ]

[[ 7.50527942e+01 -1.80588060e+01  2.63860188e-01]
 [-1.80588060e+01  4.37862218e+00 -6.58283138e-02]
 [ 2.63860188e-01 -6.58283138e-02  1.17040644e-03]]

[14.06402885 -2.06939133  0.36769797]
